"""redlines.paper -- the paper's figures and numbers, from the dashboard's own data.

    python3 -m redlines paper                # paper/fig/*.pdf + paper/numbers.tex
    python3 -m redlines paper --figs g4      # one figure
    python3 -m redlines paper --backend agg  # no TeX on this machine

Every figure is a pure render(blob) over a results/*.json mirror -- the same
bytes the page's JSX reads (tests/test_build_golden.py pins them) -- so a
paper figure cannot disagree with the dashboard. Numbers quoted in prose come
from paper/numbers.tex, generated by numbers.py from the same files, so the
prose cannot drift from the figures either.

Figures are an optional extra (`uv sync --extra paper` / `pip install
-e .[paper]`); the build stage stays stdlib-only. numbers.tex needs nothing.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..config import REPO_ROOT

# name -> (results file, module, kwargs)
FIGURES = {
    "g1": ("graph1_data.json", "graph1", {}),
    "incident_ladders": ("graph2_data.json", "incident_ladders", {}),
    "g3": ("graph3_data.json", "graph3", {}),
    "g4": ("graph4_combined.json", "graph4", {}),
    "conditional": ("conditional_data.json", "conditional", {}),
    "capability": ("capability_data.json", "capability", {}),
    # The locked StarSim causal bench (data/causal/), through its view
    # (redlines.views.causal) like every other figure -- the dashboard's
    # Graph 6 and this figure cannot disagree.
    "causal": ("causal_data.json", "causal", {}),
}
FIG_ORDER = ["g1", "incident_ladders", "g3", "g4", "conditional", "capability", "causal"]
DEFAULT_OUT = REPO_ROOT / "paper"


def load_blob(name: str, results: Path | None = None) -> dict:
    root = results or (REPO_ROOT / "results")
    f = FIGURES[name][0]
    path = (REPO_ROOT / f) if "/" in f else (root / f)
    return json.loads(path.read_text(encoding="utf-8"))


def render_figure(name: str, results: Path | None = None):
    """-> matplotlib Figure. style.use() must have been called first."""
    import importlib

    _, mod, kwargs = FIGURES[name]
    module = importlib.import_module(f".{mod}", __name__)
    return module.render(load_blob(name, results), **kwargs)


def render_all(out_dir: Path = DEFAULT_OUT, figs: list[str] | None = None,
               backend: str = "pgf", font: str = "cm", fmt: str = "pdf",
               results: Path | None = None) -> list[Path]:
    from . import style

    style.use(backend, font)
    import matplotlib.pyplot as plt

    fig_dir = Path(out_dir) / "fig"
    fig_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in (figs or FIG_ORDER):
        fig = render_figure(name, results)
        path = fig_dir / f"{name}.{fmt}"
        fig.savefig(path)
        plt.close(fig)
        written.append(path)
    return written
