"""paper/numbers.tex: every number the paper quotes, as LaTeX macros, generated
from the same results/*.json the dashboard renders.

    \\input{numbers.tex}
    ... the ensemble median is \\rl{g1:catastrophe:general:2030:median}\\% ...

Keys are colon-separated paths; \\rl{key} expands to the value, or to a bold
??key?? if the key does not exist, so a stale reference is visible in the
PDF rather than silent. Formatting rules are fixed here so the same quantity
always prints the same way (probabilities: two decimals below 1, one above;
ratios and skill scores: two decimals; correlations: signed, two decimals).

Stdlib only -- this part of `python3 -m redlines paper` needs no matplotlib.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..config import REPO_ROOT
from .dates import format_dates, month_year

HEADER = r"""% Generated by `python3 -m redlines paper` from results/*.json -- do not edit.
% Usage: \input{numbers.tex}  then  \rl{g1:catastrophe:general:2030:median}\%
% Every key below is listed in paper/README.md. An unknown key renders as ??key??.
\makeatletter
\providecommand{\rl}[1]{\@ifundefined{rl@#1}{\textbf{??#1??}}{\csname rl@#1\endcsname}}
\providecommand{\rldef}[2]{\expandafter\gdef\csname rl@#1\endcsname{#2}}
\makeatother
"""


def fmt_pct(v: float) -> str:
    return f"{v:.2f}" if v < 1 else f"{v:.1f}"


def fmt_ratio(v: float) -> str:
    return f"{v:.2f}"


def fmt_signed(v: float) -> str:
    return f"{v:+.2f}"


def fmt_int(v: float) -> str:
    return f"{int(round(v)):,}"


def fmt_big(v: float) -> str:
    """Death-equivalents: 2.7M, 26.5M, 42k."""
    if v >= 1e9:
        return f"{v / 1e9:.1f}B"
    if v >= 1e6:
        return f"{v / 1e6:.1f}M"
    if v >= 1e3:
        return f"{v / 1e3:.0f}k"
    return f"{v:.0f}"


def _load(name: str) -> dict:
    return json.loads((REPO_ROOT / "results" / name).read_text(encoding="utf-8"))


def collect(results: Path | None = None) -> dict[str, str]:
    """key -> formatted value. Pure; reads only results/*.json and data/autoarc_*.json."""
    root = results or (REPO_ROOT / "results")
    load = lambda n: json.loads((root / n).read_text(encoding="utf-8"))  # noqa: E731
    out: dict[str, str] = {}

    # --- runs / instrument ------------------------------------------------
    g1 = load("graph1_data.json")
    out["run:latest"] = (g1.get('instrumentInfo', {}).get('runDate') or g1["latest"][:10])
    out["run:dates"] = ", ".join(sorted({r[:10] for r in g1["runs"]}))
    out["run:n"] = str(len(g1["runs"]))
    out["models:n"] = str(len(g1["models"]))
    out["models:list"] = ", ".join(m["label"] for m in g1["models"])
    reps = sorted({q.get("replicates") for q in g1["questions"] if q.get("replicates")})
    out["repeats"] = "/".join(str(r) for r in reps)
    cross = json.loads((REPO_ROOT / "data" / "autoarc_crosscutting.json").read_text(encoding="utf-8"))
    ladder = json.loads((REPO_ROOT / "data" / "autoarc_ladder.json").read_text(encoding="utf-8"))
    nq = len(cross["questions"]) + len(ladder["questions"])
    cells = sum(len(q["horizons"]) for q in cross["questions"]) + sum(len(q["horizons"]) for q in ladder["questions"])
    out["questions:n"] = str(nq)
    out["cells:n"] = str(cells)
    out["ladder:causes"] = str(len(ladder.get("causes", [])) or 4)
    out["ladder:rungs"] = str(len(g1.get("rungs", [])) or 8)

    # --- Graph 1: headline forecasts ------------------------------------------
    for q in g1["questions"]:
        qid = q["id"]
        for h in q["horizons"]:
            m = q["median"].get(h)
            # One precision per cell, chosen by the median, so a CI reads
            # "0.55-1.22" rather than "0.55-1.2".
            if q["valueKind"] != "probability":
                f = fmt_big
            elif m is not None and m < 1:
                f = lambda v: f"{v:.2f}"  # noqa: E731
            else:
                f = lambda v: f"{v:.1f}"  # noqa: E731
            if m is not None:
                out[f"g1:{qid}:{h}:median"] = f(m)
            spread = []
            for s in q["series"]:
                v = s["ps"].get(h)
                if v is not None:
                    out[f"g1:{qid}:{h}:model:{_slug(s['label'])}"] = f(v)
                    spread.append((v, s["label"]))
            # The ends of the across-model spread, panel-independent, so prose
            # that quotes a range never names a model that leaves the panel.
            if spread:
                lo_v, lo_l = min(spread)
                hi_v, hi_l = max(spread)
                out[f"g1:{qid}:{h}:model:min"] = f(lo_v)
                out[f"g1:{qid}:{h}:model:max"] = f(hi_v)
                # :lo / :hi are the SAME across-model range under the names
                # the paper's brackets use. Not a confidence interval: the
                # instrument is elicited once per run.
                out[f"g1:{qid}:{h}:lo"] = f(lo_v)
                out[f"g1:{qid}:{h}:hi"] = f(hi_v)
                out[f"g1:{qid}:{h}:model:min:label"] = lo_l
                out[f"g1:{qid}:{h}:model:max:label"] = hi_l
            for hm in q.get("human") or []:
                v = hm["ps"].get(h)
                if v is not None:
                    out[f"g1:{qid}:{h}:human:{hm['panel'].lower()}:{hm['group']}"] = f(v)
        if q.get("human"):
            for hm in q["human"]:
                out[f"g1:{qid}:human:{hm['panel'].lower()}:date"] = hm["date"][:7]

    # --- Graph 2: coherence audit ---------------------------------------------
    g2 = load("graph2_data.json")
    a = g2["audit"]
    out["g2:audit:bad"] = str(a["bad"])
    out["g2:audit:n"] = fmt_int(a["n"])
    out["g2:audit:rate"] = f"{100 - a['rate']:.1f}"          # % of orderings violated
    out["g2:audit:coherent"] = f"{a['rate']:.1f}"            # % of orderings satisfied
    for k, v in a["byConstraint"].items():
        out[f"g2:audit:{k.lower()}:bad"] = str(v["bad"])
        out[f"g2:audit:{k.lower()}:n"] = fmt_int(v["n"])
    # Ladder medians: g2:ladder:<cause>:<rung>:<horizon>:median (+ :model:<slug>), in %.
    from ..conditional import expected_loss, ladder_rungs
    thresholds = ladder_rungs(ladder)
    for h, cell in g2["byHorizon"].items():
        for c in cell["causes"]:
            grids = {}
            for r in c["rungs"]:
                if r.get("median") is None:
                    continue
                k = f"g2:ladder:{c['key']}:{r['rung']}:{h}"
                out[f"{k}:median"] = fmt_pct(r["median"])
                for label, v in (r.get("per_model") or {}).items():
                    out[f"{k}:model:{_slug(label)}"] = fmt_pct(v)
                    grids.setdefault(label, {})[r['rung']] = v / 100
            shares = [value['top_share'] for grid in grids.values()
                      if (value := expected_loss(grid, thresholds)) is not None
                      and value.get('top_share') is not None]
            if shares:
                key = f"g2:loss:{c['key']}:{h}:tail"
                out[f"{key}:min"] = f"{100 * min(shares):.0f}"
                out[f"{key}:max"] = f"{100 * max(shares):.0f}"
    # Legacy per-domain aliases for bio/cyber/misalign refer to their TOP
    # incident rung (deaths OR damages), not the mortality catastrophe.
    # Never emit an AI-container alias here: g1:catastrophe:ai already names
    # the distinct 10%-of-humanity mortality question above. The unambiguous
    # g2:ladder:ai:<rung>:<h>:median keys already expose the container ladder.
    # Keep the named rung so existing per-domain prose can state its scope.
    top = g2["rungs"][-1]
    top_key = top.get("short") or top.get("key") or top.get("rung")
    out["g1:catastrophe:cause:rung"] = str(top_key)
    out["g1:catastrophe:cause:rung:label"] = str(top.get("label", top_key))
    out["mortality:run:date"] = out["run:latest"]
    for h, cell in g2["byHorizon"].items():
        for c in cell["causes"]:
            if c["key"] == "ai":
                continue
            r = next((r for r in c["rungs"] if r["rung"] == top_key and r.get("median") is not None), None)
            if r:
                out[f"g1:catastrophe:{c['key']}:{h}:median"] = fmt_pct(r["median"])

    # --- Graph 3: ForecastBench -------------------------------------------------
    g3 = load("graph3_data.json")
    for key in ("tools", "sup", "bare"):
        s = g3[key]
        out[f"g3:{key}:n"] = fmt_int(s["n"])
        out[f"g3:{key}:brier"] = f"{s['brier']:.3f}"
        out[f"g3:{key}:resolution"] = f"{s['resolution']:.3f}"
        out[f"g3:{key}:base"] = f"{100 * s['base']:.1f}"
        out[f"g3:{key}:lo:n"] = fmt_int(s["lo"]["n"])
        out[f"g3:{key}:lo:pred"] = f"{100 * s['lo']['pred']:.1f}"
        out[f"g3:{key}:lo:obs"] = f"{100 * s['lo']['obs']:.1f}"
        w = _wilson(round(s["lo"]["obs"] * s["lo"]["n"]), s["lo"]["n"])
        out[f"g3:{key}:lo:obs:lo"] = f"{100 * w[0]:.1f}"
        out[f"g3:{key}:lo:obs:hi"] = f"{100 * w[1]:.1f}"
        vm = s.get("vsMarket") or {}
        if vm:
            out[f"g3:{key}:market:n"] = fmt_int(vm["n"])
            out[f"g3:{key}:market:brier"] = f"{vm['brier']:.3f}"
            out[f"g3:{key}:market:price"] = f"{vm['market']:.3f}"
            out[f"g3:{key}:market:edge"] = f"{vm['edge']:+.3f}"
            out[f"g3:{key}:market:corr"] = f"{vm['corr']:.2f}"
        rounds = s.get("rounds") or ([s["round"]] if s.get("round") else [])
        if rounds:
            out[f"g3:{key}:rounds:n"] = str(len(rounds))
            out[f"g3:{key}:rounds:first"] = rounds[0]
            out[f"g3:{key}:rounds:last"] = rounds[-1]
    out["g3:tools:entries:n"] = str(len(g3["tools"].get("entries", [])))
    out["g3:bare:models:n"] = str(len(g3["bare"].get("models", [])))

    # --- Graph 4: simulated tail skill -----------------------------------------
    g4 = load("graph4_combined.json")
    out["g4:rho"] = fmt_signed(g4["rho"])
    out["g4:rhoClean"] = fmt_signed(g4["rhoClean"])
    out["g4:models:n"] = str(g4["nModels"])
    out["g4:modelsClean:n"] = str(g4["nModelsClean"])
    out["g4:rows:n"] = fmt_int(g4["nQuestions"])
    out["g4:base"] = f"{100 * g4['base']:.1f}"
    by = {m["label"]: m for m in g4["models"]}
    ecis = [m["eci"] for m in g4["models"]]
    out["g4:eci:min"] = str(min(ecis))
    out["g4:eci:max"] = str(max(ecis))
    for p in g4["scatter"]:
        k = _slug(p["label"])
        m = by[p["label"]]
        out[f"g4:model:{k}:eci"] = str(p["eci"])
        out[f"g4:model:{k}:bss"] = fmt_ratio(p["bss"])
        out[f"g4:model:{k}:brier"] = f"{m['brier']:.3f}"
        out[f"g4:model:{k}:n"] = fmt_int(m["n"])
        out[f"g4:model:{k}:meanPred"] = f"{100 * p['meanPred']:.0f}"
        out[f"g4:model:{k}:meanObs"] = f"{100 * p['meanObs']:.1f}"
        out[f"g4:model:{k}:sims"] = m["sims"]
    best = max(g4["scatter"], key=lambda p: p["bss"])
    out["g4:best:label"] = best["label"]
    out["g4:best:bss"] = fmt_ratio(best["bss"])
    out["g4:best:brier"] = f"{by[best['label']]['brier']:.3f}"
    out["g4:best:climBrier"] = f"{g4['base'] * (1 - g4['base']):.3f}"
    top = max(g4["scatter"], key=lambda p: p["eci"])
    out["g4:topEci:label"] = top["label"]
    out["g4:topEci:bss"] = fmt_ratio(top["bss"])
    out["g4:excluded:list"] = ", ".join(p["label"] for p in g4["scatter"] if p.get("excluded")) or "none"
    out["g4:oneSim:list"] = ", ".join(m["label"] for m in g4["models"] if m["sims"] != "civbench+starsim") or "none"

    # --- Conditional-on (policy) ----------------------------------------------
    c = load("conditional_data.json")
    out["cond:runs"] = ", ".join(r[:10] for r in c["runs"])
    out["cond:protocol"] = c["protocol"]
    out["cond:conditions:n"] = str(len(c["conditions"]))
    _condition_family(out, "cond", c["questions"])
    # --- Conditional on capability (the default variant) ----------------------
    cap = load("capability_data.json")
    v = next(v for v in cap["variants"] if v["key"] == cap["defaultVariant"])
    out["cap:variant"] = v["key"]
    out["cap:runs"] = ", ".join(r[:10] for r in v["runs"])
    out["cap:protocol"] = v["protocol"]
    out["cap:conditions:n"] = str(len(v["conditions"]))
    out["cap:models:n"] = str(len(v["models"]))
    out["cap:models:list"] = ", ".join(m["label"] for m in v["models"])
    out["cap:target"] = month_year(v["targetDate"])
    out["cap:target:months"] = str(v["targetMonths"])
    out["cap:eci:csvDate"] = cap["eci"]["csvDate"]
    out["cap:eci:latest"] = f"{cap['eci']['latest']['score']:.1f}"
    out["cap:eci:latest:date"] = cap["eci"]["latest"]["date"]
    out["cap:eci:latest:model"] = cap["eci"]["latest"]["model"]
    for c_ in v["conditions"]:
        if c_.get("level") is not None:
            out[f"cap:eci:{c_['id']}"] = f"{c_['level']:.0f}"
    fc = v["forecast"]
    for k_, val in fc["ensemble"].items():
        out[f"cap:eci:ensemble:{k_}"] = f"{val:.0f}"
    for k_, val in (fc.get("trend") or {}).items():
        out[f"cap:eci:trend:{k_}"] = f"{val:.0f}"
    out["cap:eci:trend:rate"] = f"{cap['eci']['trend']['fit']['pts_per_year']:.0f}"
    for m in fc["models"]:
        for k_ in ("p10", "p25", "p50", "p75", "p90"):
            if m.get(k_) is not None:
                out[f"cap:eci:model:{_slug(m['label'])}:{k_}"] = f"{m[k_]:.0f}"
    leap = cap.get("leap") or {}
    for d_, groups in (leap.get("dates") or {}).items():
        for g_, pc in groups.items():
            for k_, val in pc.items():
                if k_ != "n":
                    out[f"cap:eci:leap:{g_}:{d_[:4]}:{k_}"] = f"{val:.0f}"
    _condition_family(out, "cap", v["questions"])
    # Steepness: the ratio across the model's own interquartile range of
    # capability (p75 / p25) and across its tails (p90 / p10), the ECI points
    # each spans, and the compound percent change per ECI point (from the IQR).
    for q in v["questions"]:
        for h, cell in q["byHorizon"].items():
            bars = {b["id"]: b for b in cell["bars"]}
            lv = {c_["id"]: c_.get("level") for c_ in v["conditions"]}
            for name, lo_id, hi_id in (("iqr", "eci_p25", "eci_p75"), ("tails", "eci_p10", "eci_p90")):
                lo_, hi_ = bars.get(lo_id), bars.get(hi_id)
                if lo_ and hi_ and lo_.get("ratio") and hi_.get("ratio") and lv.get(lo_id) and lv.get(hi_id):
                    span = hi_["ratio"] / lo_["ratio"]
                    pts = lv[hi_id] - lv[lo_id]
                    out[f"cap:{q['id']}:{h}:{name}:ratio"] = fmt_ratio(span)
                    out[f"cap:{q['id']}:{h}:{name}:points"] = f"{pts:.0f}"
                    if name == "iqr":
                        out[f"cap:{q['id']}:{h}:perPoint:pct"] = f"{100 * (span ** (1 / pts) - 1):.1f}"
    # --- Joint elicitation and coherence (code/coherence_blob.py) -------------
    co = load("coherence_experiment.json")
    L, C = co["ladder"], co["chain"]
    out["coh:ladder:control:runs"] = ", ".join(r[:10] for r in L["controlRuns"])
    for name, st in [("control", L["control"])] + [(f"arm:{k}", v) for k, v in L["arms"].items()]:
        k = f"coh:ladder:{name}"
        out[f"{k}:ladders"] = str(st["ladders"])
        out[f"{k}:coherent"] = str(st["coherentLadders"])
        out[f"{k}:coherent:pct"] = f"{100 * st['coherentLadders'] / st['ladders']:.0f}"
        out[f"{k}:pairs"] = str(st["pairs"])
        out[f"{k}:bad"] = str(st["violatingPairs"])
        out[f"{k}:bad:pct"] = f"{100 * st['violatingPairs'] / st['pairs']:.1f}"
        out[f"{k}:cross:pairs"] = str(st["crossPairs"])
        out[f"{k}:cross:bad"] = str(st["crossViolations"])
        out[f"{k}:cross:bad:pct"] = f"{100 * st['crossViolations'] / st['crossPairs']:.1f}"
        if "fisherP" in st:
            out[f"{k}:fisherP"] = _fmt_p(st["fisherP"])
    out["coh:chain:cells"] = str(C["cells"])
    out["coh:chain:models:n"] = str(len(C["models"]))
    out["coh:chain:models:list"] = ", ".join(C["models"])
    for arm in ("sep", "joint"):
        st = C[arm]
        k = f"coh:chain:{arm}"
        out[f"{k}:chains"] = str(st["chains"])
        out[f"{k}:coherent"] = str(st["coherentChains"])
        out[f"{k}:coherent:pct"] = f"{100 * st['coherentChains'] / st['chains']:.0f}"
        out[f"{k}:pairs"] = str(st["pairs"])
        out[f"{k}:bad"] = str(st["violatingPairs"])
        out[f"{k}:bad:pct"] = f"{100 * st['violatingPairs'] / st['pairs']:.1f}"
        out[f"{k}:brier"] = f"{st['brier']:.3f}"
    bc = C["byChain"]
    out["coh:chain:brier:delta"] = f"{C['joint']['brier'] - C['sep']['brier']:+.3f}"
    out["coh:chain:byChain:n"] = str(bc["n"])
    out["coh:chain:byChain:better"] = str(bc["jointBetter"])
    out["coh:chain:byChain:worse"] = str(bc["jointWorse"])
    out["coh:chain:byChain:tied"] = str(bc["n"] - bc["jointBetter"] - bc["jointWorse"])
    out["coh:chain:byChain:medianDelta"] = f"{bc['medianDelta']:+.4f}"
    out["coh:chain:byChain:p"] = _fmt_p(bc["wilcoxonP"])
    # --- The instrument's prompt, for the appendix -----------------------------
    out.update(prompt_macros(out["run:latest"]))
    # --- StarSim causal bench (Graph 6; data/causal/ through its view) ---------
    cz = json.loads((root / "causal_data.json").read_text(encoding="utf-8"))
    h = cz["headline"]
    out["causal:rho"] = fmt_signed(h["rho"])
    out["causal:p"] = f"{h['p']:.4f}"
    out["causal:n"] = str(h["n"])
    out["causal:baselineRho"] = fmt_signed(h["baselineRho"])
    out["causal:baselineP"] = f"{h['baselineP']:.2f}"
    ms = cz["models"]
    for m in ms:
        out[f"causal:model:{_slug(m['label'])}:eci"] = f"{m['eci']:.0f}"
        out[f"causal:model:{_slug(m['label'])}:recovered"] = fmt_ratio(m["recovered"])
    best = max(ms, key=lambda m: m["recovered"])
    worst = min(ms, key=lambda m: m["recovered"])
    out["causal:best:label"] = best["label"]
    out["causal:best:recovered"] = fmt_ratio(best["recovered"])
    out["causal:worst:label"] = worst["label"]
    out["causal:worst:recovered"] = fmt_ratio(worst["recovered"])
    frontier = [m for m in ms if m["eci"] >= 155]
    out["causal:frontier:n"] = str(len(frontier))
    out["causal:frontier:min"] = fmt_ratio(min(m["recovered"] for m in frontier))
    out["causal:frontier:max"] = fmt_ratio(max(m["recovered"] for m in frontier))
    out["causal:frontier:median"] = fmt_ratio(sorted(m["recovered"] for m in frontier)[len(frontier) // 2])
    # Format only presentation metadata, after building the exact dated prompt.
    # The prompt text itself must remain a verbatim record of the instrument.
    for key in out:
        if (key.endswith((":date", ":runs", ":first", ":last", ":csvDate"))
                or key in {"run:latest", "run:dates", "prompt:today"}):
            out[key] = format_dates(out[key])
    return out


def render(results: Path | None = None) -> str:
    vals = collect(results)
    lines = [HEADER]
    for k in sorted(vals):
        lines.append(f"\\rldef{{{k}}}{{{_tex(vals[k])}}}")
    return "\n".join(lines) + "\n"


def write(path: Path, results: Path | None = None) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(results), encoding="utf-8")
    return path


def _wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """95% Wilson interval on k/n -- the same interval the Graph 3 deciles carry."""
    import math
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return c - h, c + h


def _condition_family(out: dict, prefix: str, questions: list) -> None:
    """<prefix>:<qid>:<h>:baseline and per condition {ratio,cut,level,priced,median,median:priced,
    lo,hi,lo:label,hi:label,lowered,raised} -- shared by the policy and
    capability tabs, whose blobs carry the same cell shape. lo/hi are the
    across-model range, never an interval: the instrument is elicited once
    per run (2026-09-02), so the blobs' `ci` fields are pilot-only and
    ignored here."""
    for q in questions:
        qid = q["id"]
        f = fmt_pct if q["valueKind"] == "probability" else fmt_big
        for h, cell in q["byHorizon"].items():
            out[f"{prefix}:{qid}:{h}:baseline"] = f(cell["baselineMedian"])
            for b in cell["bars"]:
                if b.get("ratio") is None:
                    continue
                k = f"{prefix}:{qid}:{h}:{b['id']}"
                # Absolute forecasts in prose need the median of conditioned
                # model levels, not baselineMedian * median(model ratios).
                median = b.get("pMedian")
                if median is not None:
                    out[f"{k}:median"] = f(median)
                    if median > 0:
                        out[f"{k}:median:priced"] = f"{100 * (1 - cell['baselineMedian'] / median):.0f}"
                out[f"{k}:ratio"] = fmt_ratio(b["ratio"])
                out[f"{k}:cut"] = f"{100 * (1 - b['ratio']):.0f}"
                # The conditioned world in the baseline's own units (ensemble
                # ratio applied to the ensemble baseline), and the cut the
                # unconditional makes FROM that world, 100*(1 - 1/ratio) --
                # for `sq` that is the mitigation the models price in.
                out[f"{k}:level"] = f(cell["baselineMedian"] * b["ratio"])
                if b["ratio"] > 0:
                    out[f"{k}:priced"] = f"{100 * (1 - 1 / b['ratio']):.0f}"
                # :lo / :hi are the across-model range of the ratio (the dots
                # on the figure), not a confidence interval.
                rs = [m["ratio"] for m in b.get("models", []) if m.get("ratio") is not None]
                if rs:
                    out[f"{k}:lo"] = fmt_ratio(min(rs))
                    out[f"{k}:hi"] = fmt_ratio(max(rs))
                    out[f"{k}:lo:label"] = min(b["models"], key=lambda m: m.get("ratio", 9e9))["label"]
                    out[f"{k}:hi:label"] = max(b["models"], key=lambda m: m.get("ratio", -9e9))["label"]
                out[f"{k}:lowered"] = str(b.get("lowered", ""))
                out[f"{k}:raised"] = str(b.get("raised", ""))


def _fmt_p(p: float) -> str:
    if p >= 0.001:
        return f"{p:.3f}"
    mant, exp = f"{p:.1e}".split("e")
    return rf"\ensuremath{{{mant} \times 10^{{{int(exp)}}}}}"   # works in text or math mode


# TeX for the prompt macros. The values are one line each (numbers.tex is one
# \rldef per line and tests/test_paper.py forbids a newline in a value): a
# paragraph gap is `\par\smallskip\noindent`, a kept line break `\newline`
# (neither takes an argument, so a following `*` bullet or `[` is text, which
# `\\` would swallow). Hard-wrapped prose is reflowed; structural lines --
# bullets, indented rows, `--- id ---`, `Field:` lines -- keep their breaks.
# They are meant for a {\ttfamily\raggedright ...} block (paper/README.md).
# (% & _ # $ are left alone: render()'s _tex escapes them in every value.)
_TEX = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}",
        "^": r"\^{}", "~": r"\~{}",
        "<": r"\textless{}", ">": r"\textgreater{}", "|": r"\textbar{}",
        "“": "``", "”": "''", "‘": "`", "’": "'",
        "—": "-{}-{}-", "–": "-{}-", "…": "...", " ": " ",
        "≥": r"\ensuremath{\geq}", "≤": r"\ensuremath{\leq}",
        "×": r"\ensuremath{\times}", "→": r"\ensuremath{\rightarrow}"}

import re as _re
# A line that starts one of these begins a new line in the typeset block.
_BREAK_BEFORE = _re.compile(
    r"^(\s*[*\-]\s|\s{2,}\S|-{3} |={5}|Horizons for this question:|Horizon:|Condition:|"
    r"Resolution criteria:|Step \d|\d{4}-\d\d-\d\d|Unconditional:|Frontier ECI|As of |"
    r"Perfect Knowledge:|Severity:|Dates:|Definitions\.|Every probability)")


def _reflow(lines: list[str]) -> list[str]:
    """Join hard-wrapped prose lines; keep structural breaks."""
    out: list[str] = []
    for raw in lines:
        if out and out[-1] and raw and not _BREAK_BEFORE.match(raw) and not out[-1].rstrip().endswith(":") \
                and not out[-1].startswith("---") and not out[-1].startswith("====="):
            out[-1] = out[-1].rstrip() + " " + raw.strip()
        else:
            out.append(raw)
    return out


def tex_escape(text: str) -> str:
    lines = []
    for raw in _reflow(text.strip("\n").split("\n")):
        s = "".join(_TEX.get(ch, ch) for ch in raw.rstrip())
        s = _re.sub(r"-{2,}", lambda m: "{}".join(m.group()), s)   # no en-dash ligature
        # Runs of spaces (indented bullets, the ECI table) survive as fixed spaces.
        s = _re.sub(r" {2,}", lambda m: r"\ " * len(m.group()), s)
        if s.startswith(" "):
            s = r"\ " + s[1:]
        bad = [ch for ch in s if ord(ch) > 127]
        if bad:
            raise ValueError(f"prompt text has unmapped non-ASCII {bad!r} in: {raw[:60]!r}")
        lines.append(s)
    out, blank = [], False
    for s in lines:
        if not s:
            blank = True
            continue
        if out:
            out.append(r"\par\smallskip\noindent " if blank else r"\newline ")
        out.append(s)
        blank = False
    return "".join(out)


def prompt_macros(run_date: str) -> dict[str, str]:
    """prompt:* -- the published instrument's prompt, sliced for the appendix.

    Built by the runner's own builder (code/run_unified.py, the combined set,
    no model called) with `today` = the latest run date, so the rolling
    horizons and the ECI target date are the ones that run saw and the file
    does not change with the calendar. The whole prompt is ~105k characters
    (35 questions with their criteria, 14 conditions), so the macros carry its
    skeleton -- system prompt, head, tail -- plus representative blocks: the
    three cross-cutting questions, one ladder rung, the shared criteria, the
    conditions preamble, the status-quo policy item, and one capability item.
    """
    import importlib.util
    from datetime import date
    spec = importlib.util.spec_from_file_location("run_unified", REPO_ROOT / "code" / "run_unified.py")
    ru = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ru)
    today = date.fromisoformat(run_date)
    policies = ru.load_policies(ru.COMBINED)
    conds = ru.expand_conditions(["all"], policies)
    groups, by_group, horizons, _, qspec = ru.load_batch(ru.LADDER, ru.CROSS, ru.UNBATCHED)
    horizons = ru.set_horizons(policies, horizons)
    prompt, n, cells = ru.build_prompt_joint(groups, by_group, horizons, qspec, conds, policies, today)
    groups_ = ru.set_groups(policies)
    out = {
        "prompt:protocol": ru.set_protocol(policies),
        "prompt:today": run_date,
        "prompt:questions:n": str(n),
        "prompt:cells:n": str(cells),
        "prompt:horizons:n": str(len(horizons)),
        "prompt:horizons:list": ", ".join(horizons),
        "prompt:conditions:n": str(len(conds) + 1),
        "prompt:conditions:policy:n": str(sum(1 for c in conds if c.get("group") == groups_[0]["key"])),
        "prompt:conditions:capability:n": str(sum(1 for c in conds if c.get("group") == groups_[1]["key"])),
        "prompt:probabilities:n": f"{cells * (len(conds) + 1):,}",
        "prompt:chars": f"{len(prompt):,}",
        "prompt:research:min": str(ru.MIN_RESEARCH),
        "prompt:rounds:max": str(ru.MAX_ROUNDS),
        "prompt:system": tex_escape(ru.SYSTEM),
    }
    # Slice the user prompt on its own section rules.
    lines = prompt.split("\n")
    first = next(i for i, l in enumerate(lines) if l.startswith("====="))
    last = max(i for i, l in enumerate(lines) if l.strip() == "=====")
    out["prompt:user:head"] = tex_escape("\n".join(lines[:first]))
    out["prompt:user:tail"] = tex_escape("\n".join(lines[last + 1:]))

    def section(title, upto=None):
        i = lines.index(f"===== {title} =====")
        j = next((k for k in range(i + 1, len(lines)) if lines[k].startswith("=====")), len(lines))
        body = lines[i + 1:j]
        if upto is not None:
            body = body[:next((k for k, l in enumerate(body) if l.startswith(upto)), len(body))]
        return "\n".join(body)

    def item(qid):
        i = next(k for k, l in enumerate(lines) if l.startswith(f"--- {qid} "))
        j = next(k for k in range(i + 1, len(lines)) if lines[k].startswith("---") or lines[k].startswith("====="))
        return "\n".join(lines[i:j])

    for qid in ("catastrophe:general", "catastrophe:ai", "disempowerment", "ladder:ai:100"):
        out[f"prompt:question:{qid}"] = tex_escape(item(qid))
    out["prompt:shared"] = tex_escape(section("APPLIES TO EVERY INCIDENT QUESTION ABOVE"))
    out["prompt:conditions:preamble"] = tex_escape(section("CONDITIONS"))
    out["prompt:conditions:policy:instruction"] = tex_escape(section("POLICY CONDITIONS", upto="---"))
    out["prompt:condition:sq"] = tex_escape(item("sq"))
    out["prompt:conditions:capability:instruction"] = tex_escape(section("CAPABILITY CONDITIONS", upto="---"))
    out["prompt:condition:eci_p50"] = tex_escape(item("eci_p50"))
    return out


def _slug(label: str) -> str:
    return label.lower().replace(" ", "-")


def _tex(s: str) -> str:
    return (s.replace("%", r"\%").replace("&", r"\&").replace("_", r"\_").replace("#", r"\#")
             .replace("$", r"\$"))
