"""Schema-checked loader for the historical severity markers.

One file, one source: data/historical_events.json is generated by
code/make_historical_events.py and may not be edited by hand —
tests/test_historical_events.py fails the build if it drifts from what the
generator produces. Same contract as redlines/questions.py, for the same
reason: the 2026-08-17 call found an eighty-fold error in a headline that had
been typed into a JSX chunk rather than joined to the data it labelled.

Every label a reader sees — the event name, its span, its range — comes from
here, never from prose typed into the page.
"""
import json

from .config import REPO_ROOT

EVENTS_PATH = REPO_ROOT / "data" / "historical_events.json"

TOP_KEYS = ("title", "provenance", "conversion", "caveat", "events")
EVENT_KEYS = ("id", "kind", "label", "short", "span", "basis", "deaths",
              "damages_usd", "severity", "source", "note", "verified")
SOURCE_KEYS = ("org", "title", "url")
BAND_KEYS = ("low", "central", "high")


def _require(d, keys, what):
    missing = [k for k in keys if k not in d]
    if missing:
        raise ValueError(f"{what} missing required key(s) {missing}: "
                         f"{sorted(d)[:8]}. Regenerate with "
                         f"python3 code/make_historical_events.py")


def load_events(path=EVENTS_PATH):
    """-> the validated marker document, events ascending by severity."""
    with open(path) as fh:
        doc = json.load(fh)
    _require(doc, TOP_KEYS, str(path))
    if not doc["events"]:
        raise ValueError(f"{path}: no events")

    seen = set()
    for ev in doc["events"]:
        _require(ev, EVENT_KEYS, f"{path} event")
        if ev["id"] in seen:
            raise ValueError(f"{path}: duplicate event id {ev['id']!r}")
        seen.add(ev["id"])
        _require(ev["source"], SOURCE_KEYS, f"{path} {ev['id']} source")
        _require(ev["severity"], BAND_KEYS, f"{path} {ev['id']} severity")
        band = ev["severity"]
        if not band["low"] <= band["central"] <= band["high"]:
            raise ValueError(f"{path}: {ev['id']} severity band not ordered: "
                             f"{band}")
        if band["low"] <= 0:
            raise ValueError(f"{path}: {ev['id']} severity must be positive "
                             f"(the axis is logarithmic): {band}")
        if ev["deaths"] is None and ev["damages_usd"] is None:
            raise ValueError(f"{path}: {ev['id']} has neither deaths nor "
                             f"damages, so it cannot be placed")

    order = [e["severity"]["central"] for e in doc["events"]]
    if order != sorted(order):
        raise ValueError(f"{path}: events not ascending by severity")
    return doc


def markers(path=EVENTS_PATH):
    """-> the display-ready marker list for Graph 2, plus its caveat.

    Trimmed to what the chart draws. The full record — every figure, its basis
    and its citation — stays in the JSON for the definitions modal and for
    anyone auditing where a band came from.
    """
    doc = load_events(path)
    return {
        "caveat": doc["caveat"],
        "conversion": doc["conversion"],
        "events": [{
            "id": e["id"],
            # "event" = a historical toll, drawn as an estimate band;
            # "reference" = a definitional mark at today's population,
            # drawn as a line. The page words its tooltip off this.
            "kind": e["kind"],
            "label": e["label"],
            "short": e["short"],
            "span": e["span"],
            "basis": e["basis"],
            "low": e["severity"]["low"],
            "central": e["severity"]["central"],
            "high": e["severity"]["high"],
            # Which leg placed it. "damages" = no deaths figure, so the
            # position is dollars / VSL; the page words the tooltip in
            # dollars for those, not in a death count it never had.
            "leg": "damages" if e["deaths"] is None else "deaths",
            "damagesUsd": (e["damages_usd"] or {}).get("central"),
            "source": e["source"]["org"],
            "sourceTitle": e["source"]["title"],
            "url": e["source"]["url"],
            "note": e["note"],
        } for e in doc["events"]],
    }
