"""Schema-checked loaders for the Auto-ARC question set, and its display labels.

Two files, one source. Both are generated by code/make_autoarc_questions.py from
the question-set author's workbook and definitions under data/auto-arc/, and
neither may be edited by hand — tests/test_autoarc_generator.py fails the build
if either drifts from what the generator produces.

  load_crosscutting()  general catastrophe, AI catastrophe, human
                       disempowerment. Severity is FIXED (project lead,
                       2026-08-18: a catastrophe is 10% of population, so there
                       is no ladder; all that varies are dates), so these are
                       three questions rather than a ladder.
  load_ladder()        the 4 x 8 incident grid, plus causes, rungs, horizons,
                       the coherence relations and the featured ids.

WHY THE LABEL HELPERS LIVE HERE. Every threshold string a human reads — a graph
title, an axis tick, a tooltip, the modal — comes from severity_label() or
horizon_label(), never from prose typed into a JSX chunk. That is not style. The
live dashboard announced "Catastrophic = >= 10 million deaths" beside a question
asking about 10% of humans alive, roughly 820 million, because the headline was
typed by hand and nothing joined it to the question it labelled. Off by eighty
times, in the headline, until it was caught by eye on the 2026-08-17 call.

Replaces the XPT-era loaders (load_starter / load_ladder over
data/starter_questions.json and data/severity_ladder_questions.json). Those
question sets are retired to archive/legacy-questions/.
"""
import json
from datetime import date

from .config import REPO_ROOT

CROSS_PATH = REPO_ROOT / "data" / "autoarc_crosscutting.json"
LADDER_PATH = REPO_ROOT / "data" / "autoarc_ladder.json"

CROSS_KEYS = ("id", "name", "short", "category", "value_kind", "severity",
              "horizons", "text", "criteria", "human")
LADDER_TOP_KEYS = ("title", "provenance", "notes", "causes", "rungs", "horizons",
                   "rolling", "fixed_horizons", "featured", "relations",
                   "questions")
LADDER_QUESTION_KEYS = ("id", "cause", "cause_label", "color", "category",
                        "value_kind", "severity", "rung", "horizons", "text",
                        "criteria", "human")
CAUSE_KEYS = ("key", "label", "color")
RUNG_KEYS = ("deaths", "damages_usd", "short", "label")


def _require(d, keys, what):
    missing = [k for k in keys if k not in d]
    if missing:
        raise ValueError(f"{what} missing required key(s) {missing}: "
                         f"{sorted(d)[:8]}. Regenerate with "
                         f"python3 code/make_autoarc_questions.py")


def load_crosscutting(path=CROSS_PATH):
    """-> the three cross-cutting questions, validated."""
    doc = json.loads(open(path).read())
    if "questions" not in doc:
        raise ValueError(f"{path}: missing top-level 'questions'")
    for q in doc["questions"]:
        _require(q, CROSS_KEYS, f"{path}: question {q.get('id', '<unknown>')!r}")
    return doc["questions"]


def load_crosscutting_doc(path=CROSS_PATH):
    """The whole cross-cutting spec, for consumers that need world_pop/notes."""
    doc = json.loads(open(path).read())
    load_crosscutting(path)
    return doc


def load_ladder(path=LADDER_PATH):
    """-> the full validated ladder spec; spec["questions"] is the 32 rungs."""
    doc = json.loads(open(path).read())
    _require(doc, LADDER_TOP_KEYS, str(path))
    for c in doc["causes"]:
        _require(c, CAUSE_KEYS, f"{path}: cause {c.get('key', '<unknown>')!r}")
    for r in doc["rungs"]:
        _require(r, RUNG_KEYS, f"{path}: rung {r!r}")
    for q in doc["questions"]:
        _require(q, LADDER_QUESTION_KEYS,
                 f"{path}: ladder question {q.get('id', '<unknown>')!r}")
    return doc


# The severity axis every chart that plots deaths shares (Graph 2's curves,
# Graph 1's and the Timeline's expected-loss rows): a hair under the 1k rung
# to a hair past Extinction (8.2B). Emitted into the blobs; no chunk types
# these numbers.
SEVERITY_AXIS = {"lo": 800, "hi": 1.4e10}


def all_questions():
    """-> {question_id: question}, both files merged.

    For consumers that resolve an id without caring which file it came from —
    the data bank, the coherence audit, the run log's metadata lookups.
    """
    out = {q["id"]: q for q in load_crosscutting()}
    out.update({q["id"]: q for q in load_ladder()["questions"]})
    return out


# ── display labels: the single source for every threshold a human reads ──────

def severity_label(q, short=False):
    """The threshold, rendered. Never type one of these into a page chunk.

    Three severity kinds, because the set genuinely has three:
      deaths_or_damages  a ladder rung: "1M deaths or $10T"
      population_share   the catastrophe questions: "10% of population". This
                         one FLOATS — it resolves on a share, so its
                         death-equivalent moves with population while the rungs
                         stay put. It is an anchor on the severity axis, not a
                         rung of it.
      none               human disempowerment, which has no severity axis at all
    """
    s = q["severity"]
    if short:
        return s["short"]
    # No severity axis (human disempowerment): no label at all, rather than the
    # ladder's "not applicable" placeholder in an eyebrow (project lead, 2026-09-02).
    if s.get("kind") == "none":
        return None
    return s["label"]


def severity_deaths(q):
    """Where this question sits on the log-death axis, or None.

    A population share is converted through its stored deaths_equiv rather than
    recomputed, so the axis position and the label can never disagree.
    """
    s = q["severity"]
    if s["kind"] == "deaths_or_damages":
        return s["deaths"]
    if s["kind"] == "population_share":
        return s["deaths_equiv"]
    return None


def horizon_label(h, spec=None, run_date=None):
    """'2030' -> 'by 2030'; '6mo' -> 'within 6 months (by 2027-02-18)'.

    A rolling horizon has no fixed year, so a label that only said "6mo" would
    leave a reader unable to tell what a plotted point actually claims. When a
    run date is known the absolute date is shown alongside — that is the whole
    point of tracking it (project lead, 2026-08-18: track the ABSOLUTE
    resolution date so the forecast can be seen and resolved over time).
    """
    roll = _rolling(spec).get(h)
    if not roll:
        return f"by {h}"
    if run_date is None:
        return roll["label"]
    return f"{roll['label']} (by {resolves_on(h, run_date, spec)})"


def _rolling(spec):
    if spec is None:
        spec = load_ladder()
    return {r["id"]: r for r in spec.get("rolling", [])}


def resolves_on(h, run_date, spec=None):
    """-> ISO date this horizon resolves on, for a run made on `run_date`.

    Fixed horizons resolve at the end of their year. Rolling ones resolve
    `months` after the run, which is why every forecast row has to carry this:
    a rolling forecast made in August and one made in October are different
    questions, and only the stamped date can tell them apart later.
    """
    roll = _rolling(spec).get(h)
    if not roll:
        return f"{h}-12-31"
    if isinstance(run_date, str):
        run_date = date.fromisoformat(run_date[:10])
    m = run_date.month - 1 + roll["months"]
    y, m = run_date.year + m // 12, m % 12 + 1
    # Clamp the day, so a run on the 31st does not fall off a short month.
    d = min(run_date.day, [31, 29 if y % 4 == 0 and (y % 100 or not y % 400)
                           else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][m - 1])
    return f"{y:04d}-{m:02d}-{d:02d}"


def is_future(h, spec=None, today=None):
    """Is this horizon still ahead of us?

    Views drop past horizons so a chart does not plot a forecast for a year
    that has already happened. The old test was `int(h) > date.today().year`,
    which raises on a rolling horizon — "6mo" is not an integer, and it is
    always in the future by construction.
    """
    if _rolling(spec).get(h):
        return True
    return int(h) > (today or date.today()).year


def horizon_sort_key(h, spec=None):
    """Order horizons by the date they resolve, not by their string.

    '6mo' and '12mo' sort before '2028' by meaning and after it by ASCII. The
    coherence audit walks adjacent horizons to check that a cumulative
    probability never falls, so getting this backwards would report violations
    that are only a sort order.
    """
    roll = _rolling(spec).get(h)
    return (0, roll["months"]) if roll else (1, int(h))


# ── human baselines ─────────────────────────────────────────────────────────
#
# Two files, one chain. The workbook's "Human comparisons (Project)" column says
# WHICH of our question x horizon cells a prior FRI panel has answered and by
# which panel; the generator carries that column into each question's
# `human_comparisons`, and code/fetch_human_baselines.py goes to those panels'
# own data and writes the numbers here. So a baseline exists on this dashboard
# only because a row in her workbook asked for one.
#
# The old shape was {"super": x, "expert": y, "source": "XPT 2022"} — two
# groups, one panel, a panel name that four surfaces printed as a constant. It
# cannot hold what her column actually points at: the catastrophe pair has TWO
# panels at every horizon (XPT 2022 and LEAP 2026), and LEAP reports three
# groups, one of them the general public. A view that wants "the" human number
# now has to choose which panel and which group, in the open.

BASELINES_PATH = REPO_ROOT / "data" / "human_baselines.json"


def load_human_baselines(path=BASELINES_PATH):
    """-> the fetched baselines doc, or an empty one if it has not been pulled.

    Absent is a real state, not an error: the file is a committed artifact
    refreshed by hand from the FRI warehouse, and the box that runs the weekly
    forecast has no warehouse credentials. A checkout without it should render
    a dashboard with no human numbers, not fail to build.
    """
    if not path.exists():
        return {"baselines": [], "unavailable": [], "generated_at": None}
    doc = json.loads(open(path).read())
    for b in doc.get("baselines", []):
        _require(b, ("question_id", "horizon", "project", "groups",
                     "elicited", "source_question"),
                 f"{path}: baseline {b.get('question_id', '<unknown>')!r}")
    return doc


def human_baselines(question_id, horizon, doc=None):
    """Every human panel that answered `question_id` at `horizon`, unadjusted.

    A LIST, because a cell can have more than one and they disagree: at 2100
    the XPT experts said 20.85% where LEAP's said 10%, four years apart, on
    wordings that are close but not the same. Collapsing them to one number
    would be a judgement about which panel to believe, made where nobody can
    see it. Each entry carries the question its panel answered.
    """
    doc = load_human_baselines() if doc is None else doc
    return [b for b in doc.get("baselines", [])
            if b["question_id"] == question_id and b["horizon"] == str(horizon)]


def human_comparisons_wanted(q):
    """-> {horizon: [project, ...]}, straight from her workbook column.

    What SHOULD have a human number, whether or not we have pulled it yet. The
    difference between this and human_baselines() is the honest gap, and the
    page should be able to say so rather than showing a silent blank.
    """
    return q.get("human_comparisons") or {}


def cause_category(cause):
    """The risk-category name for an incident cause, read from the SSOT.

    The ladder spec carries two names per cause: `sheet` is the workbook's own
    'Category' column (AI-related incident / Biorisk / Cyber / Misalignment) and
    `label` is a longer display phrasing. The category a reader sees must be the
    same on every panel, so both Graph 1's rail and Graph 2's curves take it from
    here — one definition, sourced from the workbook, rather than each view
    picking a field. Falls back to `label` if a cause carries no sheet name.
    The container cause (the set's "AI-related incident", which contains the
    other three by definition) reads "Any AI-related incident" on every panel
    (a reviewer, 2026-08-31, asked for the "Any" for clarity). Display
    only: the prompt's group headings take the ladder's `label`, not this.
    """
    name = cause.get("sheet") or cause["label"]
    return f"Any {name}" if cause.get("container") and not name.lower().startswith("any ") else name
